FROM nginx:alpine

# Copiar archivos del build
COPY dist /usr/share/nginx/html

# Configuración para SPA
RUN echo 'server { \
    listen 80; \
    location / { \
        root /usr/share/nginx/html; \
        index index.html; \
        try_files $uri $uri/ /index.html; \
    } \
}' > /etc/nginx/conf.d/default.conf
